In [8]:
import numpy as np

# Set NumPy to display all numbers with 4 decimal places
np.set_printoptions(precision=4, suppress=True)

# Learning Rate
lr = 0.75

# Inputs and Outputs of XOR
X = np.array([[0., 0.],
              [0., 1.],
              [1., 0.],
              [1., 1.]])
print(f'X:\n{X}\n')

Y = np.array([[0.],
              [1.],
              [1.],
              [0.]])
print(f'Y:\n{Y}\n')

# Weights and Biases
W1 = np.array([
    [0.2985, -0.5792], 
    [0.0913, 0.4234]
])
print(f'W1:\n{W1}\n')

W2 = np.array([
    [0.5266, 0.2958]
])
print(f'W2:\n{W2}\n')

B1 = np.array([-0.4939, 0.189])
print(f'B1:\n{B1}\n')

B2 = np.array([0.6358])
print(f'B2:\n{B2}\n')

X:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]

Y:
[[0.]
 [1.]
 [1.]
 [0.]]

W1:
[[ 0.2985 -0.5792]
 [ 0.0913  0.4234]]

W2:
[[0.5266 0.2958]]

B1:
[-0.4939  0.189 ]

B2:
[0.6358]



## Forward Pass

In [9]:
# Layer 1
Z1 = X @ W1.T
print(f'Z1 pre bias:\n{Z1}\n')
Z1 = Z1 + B1
print(f'Z1:\n{Z1}\n')
H1 = np.maximum(0.5 * Z1, Z1)
print(f'H1:\n{H1}\n')

# Layer 2
Z2 = H1 @ W2.T
print(f'Z2 pre bias:\n{Z2}\n')
Z2 = Z2 + B2
print(f'Z2:\n{Z2}\n')
H2 = np.maximum(0.5 * Z2, Z2)
print(f'H2:\n{H2}\n')

Z1 pre bias:
[[ 0.      0.    ]
 [-0.5792  0.4234]
 [ 0.2985  0.0913]
 [-0.2807  0.5147]]

Z1:
[[-0.4939  0.189 ]
 [-1.0731  0.6124]
 [-0.1954  0.2803]
 [-0.7746  0.7037]]

H1:
[[-0.247   0.189 ]
 [-0.5366  0.6124]
 [-0.0977  0.2803]
 [-0.3873  0.7037]]

Z2 pre bias:
[[-0.0741]
 [-0.1014]
 [ 0.0315]
 [ 0.0042]]

Z2:
[[0.5617]
 [0.5344]
 [0.6673]
 [0.64  ]]

H2:
[[0.5617]
 [0.5344]
 [0.6673]
 [0.64  ]]



## Loss Calculation

In [10]:
# MSE loss calculation (not needed for training)
loss = np.mean((Y - H2) ** 2)
print(f'{loss:.4f}')

0.2631


## Backwards Pass

In [11]:
# Long Chain Calculation
dL_dH2 = 2*(H2 - Y)/len(Y)   # Derivative of loss with respect to H2
print(f'dL/dH2:\n{dL_dH2}\n')

dL_dZ2 = np.multiply(dL_dH2, np.where(Z2 > 0, 1, 0.5))
print(f'dL/dZ2:\n{dL_dZ2}\n')

dL_dH1 = dL_dZ2 @ W2
print(f'dL/dH1:\n{dL_dH1}\n')

dL_dZ1 = np.multiply(dL_dH1, np.where(Z1 > 0, 1, 0.5))
print(f'dL/dZ1:\n{dL_dZ1}\n')

# This one is not needed for training
dL_dX = dL_dZ1 @ W1
print(f'dL/dX:\n{dL_dX}\n')

dL/dH2:
[[ 0.2808]
 [-0.2328]
 [-0.1664]
 [ 0.32  ]]

dL/dZ2:
[[ 0.2808]
 [-0.2328]
 [-0.1664]
 [ 0.32  ]]

dL/dH1:
[[ 0.1479  0.0831]
 [-0.1226 -0.0689]
 [-0.0876 -0.0492]
 [ 0.1685  0.0947]]

dL/dZ1:
[[ 0.0739  0.0831]
 [-0.0613 -0.0689]
 [-0.0438 -0.0492]
 [ 0.0843  0.0947]]

dL/dX:
[[ 0.0297 -0.0077]
 [-0.0246  0.0063]
 [-0.0176  0.0045]
 [ 0.0338 -0.0087]]



In [12]:
# Leaf Node Calculations
dL_dW2 = dL_dZ2.T @ H1
print(f'dL/dW2:\n{dL_dW2}\n')

dL_dB2 = dL_dZ2.sum(axis=0)
print(f'dL/dB2:\n{dL_dB2}\n')

dL_dW1 = dL_dZ1.T @ X
print(f'dL/dW1:\n{dL_dW1}\n')

dL_dB1 = dL_dZ1.sum(axis=0)
print(f'dL/dB1:\n{dL_dB1}\n')

dL/dW2:
[[-0.0521  0.0891]]

dL/dB2:
[0.2017]

dL/dW1:
[[0.0405 0.023 ]
 [0.0454 0.0258]]

dL/dB1:
[0.0531 0.0597]



## Update Parameters

In [13]:
W1_new = W1 - lr * dL_dW1
print(f'W1_new:\n{W1_new}\n')

B1_new = B1 - lr * dL_dB1
print(f'B1_new:\n{B1_new}\n')

W2_new = W2 - lr * dL_dW2
print(f'W2_new:\n{W2_new}\n')

B2_new = B2 - lr * dL_dB2
print(f'B2_new:\n{B2_new}\n')

W1_new:
[[ 0.2682 -0.5964]
 [ 0.0572  0.4041]]

B1_new:
[-0.5337  0.1443]

W2_new:
[[0.5657 0.229 ]]

B2_new:
[0.4846]



In [14]:
# Leaf Node Calculations (Tiling)
dL_dW2 = dL_dZ2[:2].T @ H1[:2]
print(f'dL/dW2:\n{dL_dW2}\n')

# Update W2
W2_new_tiled = W2 - lr * dL_dW2
print(f'W2_new:\n{W2_new_tiled}\n')

# Leaf Node Calculations (Tiling)
dL_dW2 = dL_dZ2[2:4].T @ H1[2:4]
print(f'dL/dW2:\n{dL_dW2}\n')

# Update W2
W2_new_tiled = W2_new_tiled - lr * dL_dW2
print(f'W2_new:\n{W2_new_tiled}\n')


dL_dW1 = dL_dZ1[:2].T @ X[:2]
print(f'dL/dW1:\n{dL_dW1}\n')

# Update W1
W1_new_tiled = W1 - lr * dL_dW1
print(f'W1_new:\n{W1_new_tiled}\n')

# Leaf Node Calculations (Tiling)
dL_dW1 = dL_dZ1[2:4].T @ X[2:4]
print(f'dL/dW1:\n{dL_dW1}\n')

# Update W1
W1_new_tiled = W1_new_tiled - lr * dL_dW1
print(f'W1_new:\n{W1_new_tiled}\n')

dL/dW2:
[[ 0.0556 -0.0895]]

W2_new:
[[0.4849 0.3629]]

dL/dW2:
[[-0.1077  0.1786]]

W2_new:
[[0.5657 0.229 ]]

dL/dW1:
[[ 0.     -0.0613]
 [ 0.     -0.0689]]

W1_new:
[[ 0.2985 -0.5332]
 [ 0.0913  0.475 ]]

dL/dW1:
[[0.0405 0.0843]
 [0.0454 0.0947]]

W1_new:
[[ 0.2682 -0.5964]
 [ 0.0572  0.4041]]



## Hardware Co-Verification

Validate the **systolic array RTL** (`systolic.sv`) against this numpy golden model.

The 2×2 systolic array computes `Z1 = X @ W1ᵀ` (pre-bias) in **Q8.8 fixed-point**:

| Signal | Meaning |
|---|---|
| `sys_data_out_21` | Column-1 output  →  `Z1[:, 0]` |
| `sys_data_out_22` | Column-2 output  →  `Z1[:, 1]` |

Weight layout in hardware (loaded via `sys_accept_w`):
- **pe11** ← `W1[0][0]`,  **pe21** ← `W1[0][1]`  (column-1, staggered)
- **pe12** ← `W1[1][0]`,  **pe22** ← `W1[1][1]`  (column-2, staggered)


In [ ]:
# ── Q8.8 Fixed-Point Helpers (mirrors tiny-tpu fixedpoint.sv) ──────────────
FRAC = 8
SCALE = 1 << FRAC   # 256

def f2q(x):
    """Float → Q8.8 signed 16-bit integer (Python int, sign-extended)."""
    v = int(round(x * SCALE)) & 0xFFFF
    return v - 0x10000 if v >= 0x8000 else v

def q2f(v):
    """Q8.8 signed 16-bit integer → float."""
    v = int(v) & 0xFFFF
    return (v - 0x10000 if v >= 0x8000 else v) / SCALE

def q2hex(v):
    """Q8.8 signed 16-bit integer → 4-digit hex string."""
    return f"0x{int(v) & 0xFFFF:04X}"

def pe_mac(data_in, weight, psum=0.0):
    """
    Single PE MAC in Q8.8:
      psum_out = psum_in + (data_in * weight)
    Matches pe.sv: product = (a_reg * b_reg) >>> FRAC_BITS, then add psum.
    """
    d = f2q(data_in)
    w = f2q(weight)
    p = f2q(psum)
    product = (d * w) >> FRAC          # Q16.16 → Q8.8
    result   = (p + product) & 0xFFFF  # 16-bit truncate
    return q2f(result)                 # back to float for readability

print("Q8.8 helpers loaded.")
print(f"  Example: f2q(0.2985) = {f2q(0.2985)}  (0x{f2q(0.2985)&0xFFFF:04X})")
print(f"  Example: q2f(0x{f2q(0.2985)&0xFFFF:04X}) = {q2f(f2q(0.2985)):.4f}")


In [ ]:
# ── Systolic Array Golden Model ─────────────────────────────────────────────
# Simulates the 2×2 systolic array computing Z1 = X @ W1ᵀ sample-by-sample.
#
# For each sample i, inputs are staggered by 1 cycle:
#   Cycle 0 → pe11 sees X[i][0],   pe12 sees X[i][0]  (psum_in = 0)
#   Cycle 1 → pe21 sees X[i][1],   pe22 sees X[i][1]  (psum_in from row-1 PE)
#
# Column-1:  sys_data_out_21[i] = pe21 psum = X[i,0]*W1[0,0] + X[i,1]*W1[0,1]
# Column-2:  sys_data_out_22[i] = pe22 psum = X[i,0]*W1[1,0] + X[i,1]*W1[1,1]

Z1_pre_bias = X @ W1.T   # numpy reference

hw_Z1   = []   # Q8.8-simulated floating-point result
hw_int  = []   # raw Q8.8 integers (what the waveform shows)
hw_hex  = []   # hex strings for waveform / simulator comparison

for i in range(len(X)):
    # Column 1: pe11 → pe21
    c1 = pe_mac(X[i][0], W1[0][0])            # pe11
    c1 = pe_mac(X[i][1], W1[0][1], c1)        # pe21 accumulates

    # Column 2: pe12 → pe22
    c2 = pe_mac(X[i][0], W1[1][0])            # pe12
    c2 = pe_mac(X[i][1], W1[1][1], c2)        # pe22 accumulates

    hw_Z1.append([c1, c2])
    hw_int.append([f2q(c1) & 0xFFFF, f2q(c2) & 0xFFFF])
    hw_hex.append([q2hex(f2q(c1)), q2hex(f2q(c2))])

hw_Z1 = np.array(hw_Z1)

print("=" * 60)
print(f"{'Sample':<8} {'numpy Z1[:,0]':>14} {'HW Z1[:,0]':>12}  │  {'numpy Z1[:,1]':>14} {'HW Z1[:,1]':>12}")
print("-" * 60)
for i in range(len(X)):
    print(f"X[{i}]    {Z1_pre_bias[i,0]:>14.4f} {hw_Z1[i,0]:>12.4f}  │  "
          f"{Z1_pre_bias[i,1]:>14.4f} {hw_Z1[i,1]:>12.4f}")

print("\nExpected RTL output (Q8.8 hex — read off waveform / cocotb):")
print(f"{'Sample':<8} {'sys_data_out_21':>17} {'sys_data_out_22':>17}")
print("-" * 45)
for i in range(len(X)):
    print(f"X[{i}]    {hw_hex[i][0]:>17} {hw_hex[i][1]:>17}")


In [ ]:
# ── Quantization Error Check ────────────────────────────────────────────────
# Q8.8 has a resolution of 1/256 ≈ 0.0039.
# Any difference > 0.0039 means a logic bug, not just rounding.

TOL = 1.5 / SCALE   # 1.5 LSBs tolerance (generous, accounts for rounding both inputs)

errors      = np.abs(Z1_pre_bias - hw_Z1)
max_err     = errors.max()
all_within  = bool((errors <= TOL).all())

print(f"Q8.8 resolution (1 LSB) : {1/SCALE:.6f}")
print(f"Tolerance (1.5 LSBs)    : {TOL:.6f}")
print(f"Max quantization error  : {max_err:.6f}")
print()
if all_within:
    print("✓  All samples within tolerance — golden model matches hardware arithmetic.")
else:
    print("✗  Some samples exceed tolerance — investigate!")
    bad = np.argwhere(errors > TOL)
    for idx in bad:
        i, j = idx
        print(f"   Sample {i}, col {j}: numpy={Z1_pre_bias[i,j]:.4f}  hw={hw_Z1[i,j]:.4f}  "
              f"err={errors[i,j]:.6f}")

print()
print("Error matrix (numpy vs Q8.8 HW):")
print(errors)


In [ ]:
# ── Paste RTL output here to verify ─────────────────────────────────────────
# After running the cocotb simulation (make sim_systolic), paste the observed
# sys_data_out_21 and sys_data_out_22 values (as 16-bit unsigned hex/int)
# into the lists below. Run the cell to verify against the golden model.
#
#   Example (copy from waveform / cocotb print):
#     rtl_col1 = [0xFF80, 0xFFA6, 0x004C, 0xFF40]
#     rtl_col2 = [0x0017, 0x006C, 0x0017, 0x006C]

rtl_col1 = []   # ← paste sys_data_out_21 values here (one per sample)
rtl_col2 = []   # ← paste sys_data_out_22 values here (one per sample)

if len(rtl_col1) == len(X) and len(rtl_col2) == len(X):
    rtl_Z1 = np.array([[q2f(rtl_col1[i]), q2f(rtl_col2[i])] for i in range(len(X))])
    rtl_err = np.abs(Z1_pre_bias - rtl_Z1)

    print(f"{'Sample':<8} {'Expected c1':>12} {'RTL c1':>12}  │  {'Expected c2':>12} {'RTL c2':>12}")
    print("-" * 62)
    for i in range(len(X)):
        ok1 = "✓" if rtl_err[i,0] <= TOL else "✗"
        ok2 = "✓" if rtl_err[i,1] <= TOL else "✗"
        print(f"X[{i}]    {hw_Z1[i,0]:>12.4f} {rtl_Z1[i,0]:>11.4f}{ok1}  │  "
              f"{hw_Z1[i,1]:>12.4f} {rtl_Z1[i,1]:>11.4f}{ok2}")

    if (rtl_err <= TOL).all():
        print("\n✓  RTL output matches golden model — systolic array PASS.")
    else:
        print("\n✗  Mismatch detected — check waveform / RTL logic.")
else:
    print("Paste RTL values into rtl_col1 / rtl_col2 above, then re-run.")
    print(f"  Expected {len(X)} values per column.")
    print()
    print("Expected values to assert in sim:")
    for i in range(len(X)):
        print(f"  X[{i}]:  sys_data_out_21 = {hw_hex[i][0]}  ({hw_Z1[i,0]:+.4f})  |  "
              f"sys_data_out_22 = {hw_hex[i][1]}  ({hw_Z1[i,1]:+.4f})")
